# Copy the configuration below and add it to your
# ~/.config/kitty/kitty.conf file

## Root Loops color scheme
## via https://rootloops.sh?sugar=8&colors=7&sogginess=4&flavor=0&fruit=2&milk=1

# The basic colors
background              #2d1e12
foreground              #e9d1be
selection_background    #e9d1be
selection_foreground    #2d1e12

# Cursor colors
cursor_text_color       #2d1e12
cursor                  #c29774

# URL underline color when hovering with mouse
url_color               #f1b686

# Kitty window border colors
active_border_color     #c29774
inactive_border_color   #74543a
bell_border_color       #ed8cab

# Tab bar colors
active_tab_foreground   #e9d1be
active_tab_background   #2d1e12
inactive_tab_foreground #473120
inactive_tab_background #c29774
tab_bar_background      #2d1e12

# Colors for marks (marked text in the terminal)
mark1_foreground #e9d1be
mark1_background #f3adc2
mark2_foreground #e9d1be
mark2_background #f1b686
mark3_foreground #e9d1be
mark3_background #b9d167

# The 16 terminal colors

# black
color0 #473120
color8 #74543a

# red
color1 #ed8cab
color9 #f3adc2

# green
color2  #a4ba54
color10 #b9d167

# yellow
color3  #e59b5d
color11 #f1b686

# blue
color4  #6db7e9
color12 #95cbf3

# magenta
color5  #b99ded
color13 #ccb8f3

# cyan
color6  #56c4b1
color14 #6adbc7

# white
color7  #c29774
color15 #e3c4ac
